### ISSUE TITLE
Фон для панели nav

### ISSUE THREAD

**Issue by Gr0mi4** [Gr0mi4/Hello-World#10]
Мне интересно, я могу задать другой размер и форму бэкграунду который подсвечивается у меня при выборе менюшки в панели навигации??
![Screenshot_1](https://user-images.githubusercontent.com/50546979/59255811-4e87ea00-8c3b-11e9-8bd7-8f707a5a6ff1.jpg)
Что бы например это был не прямоугольник, а овал?

**Comment by Demven** [comment]
Да, можешь сделать овал или любые закругления через свойство `border-radius`

**Comment by Gr0mi4** [comment]
Ок, попробовал зацени)
