### ISSUE TITLE
`<meta name=description>` и `<meta name="keywords">`

### ISSUE THREAD

**Issue by Gr0mi4** [Gr0mi4/Hello-World#11]
Привет! прочитал на академии про `description` и `keywords`. Подскажи, в них есть реальная необходимость, или это уже отмирающий атавизм?

**Comment by Demven** [comment]
Это очень нужные и важные метатеги. Но они нужны для роботов, а не для людей) 
Когда ты кидаешь ссылку например в телеграм, телеграм запрашивает твою страницу, извлекает оттуда картинку, тайтл и описание из твоих метатегов.

**Comment by Gr0mi4** [comment]
Короче мы их добавляем на сайт да?

**Comment by Demven** [comment]
Пока не нужно

**Comment by Demven** [comment]
У нас по плану это будет отдельная тема

**Comment by Demven** [comment]
А, вижу ты уже добавил, хорошо
