### ISSUE TITLE
По поводу нижних и правых отступов

### ISSUE THREAD

**Issue by Gr0mi4** [Gr0mi4/Hello-World#12]
> Первое и самое главное правило для отступов – не задавать отступы снизу и справа без необходимости. Элементы должны определять свое положение относительно предыдущего элемента и не влиять на последующие.
> Поясню: если элементы располагаются в колонке - можно задать margin-top, но задавать margin-bottom не стоит (без острой необходимости). Если элементы располагаются в ряду (как у тебя с артиклом и рекламой) - нужно задавать отступы между элементами через margin-left.
> Это нужно для изоляции компонентов, чтобы они не влияли друг на друга.

Что значит без необходимости? Если у меня текст располагается внизу блока, а я хочу что бы он располагался в середине это необходимость? Напрмер:
![image](https://user-images.githubusercontent.com/50546979/59588320-00b62a80-90f0-11e9-9777-3405d3fc96ff.png)
Я как ты и сказал пересматриваю все элементы и удаляю оттуда нижние и правые отступы. Вопрос: Вот сейчас копирайт уехал ниже чем мне бы хотелось. Я могу задать например `padding: 10px;` ,
Могу задать `box-sizing: content box; padding 10px;` для скажем всего блока `footer`, могу задать высоту строки равную высоте блока (как мы делали с `.advertisment`), какой вариант будет правильным? (ставлю на третий)

**Comment by Demven** [comment]
Это будет сложно объяснить в комментарии, я постараюсь заснять видео где на бумаге покажу
