### ISSUE TITLE
> После моего видео хотелось бы увидеть как ты переработал все отступы в документе. Пока я этого не вижу. Это последнее что нужно сделать тебе перед тем как все станет совсем идеально и мы смержим)

### ISSUE THREAD

**Issue by Gr0mi4** [Gr0mi4/Hello-World#13]
> После моего видео хотелось бы увидеть как ты переработал все отступы в документе. Пока я этого не вижу. Это последнее что нужно сделать тебе перед тем как все станет совсем идеально и мы смержим)
> 
> 1. Вот смотри вот здесь нужен margin вместо padding:
> 
> <img alt="image" width="708" src="https://user-images.githubusercontent.com/4939520/59696547-34f61d80-91ba-11e9-84ab-20c2889445e0.png">
> 
> <img alt="image" width="259" src="https://user-images.githubusercontent.com/4939520/59696567-40494900-91ba-11e9-8618-15cfb03fa044.png">
> 
> 1. Потом в статье у тебя используются для многих элементов дефолтные браузерные стили. Отступы задает браузер и стоило бы  их переопределить на то что нужно именно тебе.
> 
> .headline:
> <img alt="image" width="518" src="https://user-images.githubusercontent.com/4939520/59696729-8c948900-91ba-11e9-8631-1e14d4429502.png">
> Давай сделаем заголовок в один уровень с рекламой и выровняем по левому краю, вообще без отступов. (`margin: 0;`)
> 
> .text:
> <img alt="image" width="190" src="https://user-images.githubusercontent.com/4939520/59696942-fc0a7880-91ba-11e9-9d67-e657b8b7f918.png">
> 
> Нужно задать только марджин-топ и в то же время сбросить дефолтный марджин. Давай между текстовыми элементами у нас будет отступ 24px. Тогда нужно задать `margin: 24px 0 0;`.
> Давай еще поправим немного стили для текста и добавим еще вот это:
> 
> ```
>     font-family: Georgia;
>     font-size: 18px;
>     line-height: 24px;
> ```
> 
> .headline-2:
> <img alt="image" width="224" src="https://user-images.githubusercontent.com/4939520/59697209-76d39380-91bb-11e9-84ad-cdb558774e22.png">
> Уберем margin кроме как сверху 24px: `margin: 24px 0 0;` и еще `font-size: 24px; line-height: 30px;`
> 
> .numbered-list, .unnumbered-list: те же стили что и для .text
> 
> .wisdom
> Давай сделаем по красоте и во-первых используем более подходящий элемент `blockquote`, а во-вторых добавим стилей:
> 
> ```
> .quote {
>   width: 600px;
>   margin: 32px auto 0;
>   padding: 24px;
>   font-family: Helvetica;
>   font-size: 24px;
>   font-style: italic;
>   line-height: 32px;
>   text-align: center;
>   border: 4px dashed #bf0000;
> }
> ```
> 
> .ferrariimg:
> Во-первых, опять-таки, класс должен определять сущность, а не содержимое (если только это не уникальная сущность и никогда не меняет содержимое). В статье может быть любая картинка и задавать для каждой уникальное имя, но при этом одни и те же стили - очень плохая идея.
> Нужно переименовать в `image`, добавить верхний отступ и отцентрировать:
> 
> ```
>     margin: 40px auto 0;
>     display: block;
> ```
Перевожу в Issue, есть вопросы

_Originally posted by @Gr0mi4 in https://github.com/Gr0mi4/Hello-World/pull/4#issuecomment-503421775_

**Comment by Gr0mi4** [comment]
Смотри, вторая картинка. Если заменить паддинг на марджин то получается белый фон над навигацией, а я хотел именно что бы начиналось с бирюзового фона. Я задал через `.main-header {
  background-color: #2BC6DC;
  box-sizing: content-box;
  padding: 10px;`
создав новый класс в `header`, это правильно?

**Comment by Demven** [comment]
"получается белый фон над навигацией, а я хотел именно что бы начиналось с бирюзового фона"
Ну вот видишь – сразу вскрылись проблемы с предыдущим подходом :)
Почему ты задавал background для отдельных дочерних элементов, если цвет фона - это свойство всего <header>? По дизайну видно что весь  хедер бирюзовый, а не отдельные элементы.

**Comment by Gr0mi4** [comment]
Привет! С последнего ревью прошел уже месяц, у меня процесс вспоминания идет туговато =)) Слушай, я задал для моей цитаты класс `<blockquote>` и теперь в элементе есть свои марджины и свой паддинг, который появился именно из стилей элемента `<blockquote>`. Мне кажется есть необходимость в том что бы переопределить заданные браузером значения `<margin>` и `<padding>`, потому что сейчас из-за того что у меня задан марджин для следующего `.text` расстояния у меня не одинаковые (см. картинку 2).
Я переопределяю значения марджин и паддинг а ты скажи - правильно я подумал или нет.
P.S. И кстати - когда мы задавали размеры `<main>` через `box-sizing` мы задали `padding` со всех сторон, но так было нарисовано и у тебя в задании.  Я так понимаю это не считается ошибкой? Почему?
![image](https://user-images.githubusercontent.com/50546979/61613592-67d47b00-ac6a-11e9-8ae4-38381a180cf1.png)
![image](https://user-images.githubusercontent.com/50546979/61613923-314b3000-ac6b-11e9-8fca-7b68518b5b3c.png)

**Comment by Demven** [comment]
@Gr0mi4 Да, нужно переопределять дефолтные браузерные стили если они тебе не подходят.

**Comment by Gr0mi4** [comment]
Нет, по ходу я нечаянно его закрыл) Но я понял с переопределением, а как быть с box-sizing'ом?

**Comment by Demven** [comment]
Не уверен что понял твой вопрос насчет box-sizing, но padding мы задали со всех сторон, чтобы контент внутри этого контейнера никогда не начинался от края экрана (но это будет работать только если задать ширину 100% а не в пикселях как у нас сейчас). Это нормально и даже правильно само собой, но в нашем случае не играет особой роли. Чуть позже когда будем адаптировать сайт под все девайсы - это будет полезно.
