### ISSUE TITLE
По поводу разделения компонентов пустыми строками

### ISSUE THREAD

**Issue by Gr0mi4** [Gr0mi4/Hello-World#14]
Я пересмотрел сегодня все твои комменты по поводу моего кода... и пришел к выводу что я рукожоп и как ты меня вообще терпишь))) Кроме шуток ты оставлял несколько комментов по поводу пустых строк, по большому счёту это последнее недопонимание с которым мы не разобрались, поэтому хочу ещё раз уточнить правильно ли я тебя понял: 
Мы говорим про компоненты исключительно в `<body>`. В нем я выделил следующие компоненты - в <header> я отделил друг от друга `<p> <nav> <ul>`, в <main> я отделил `<article> <aside>` внутри `<aside>` ничего нет, а внутри `<article>` я отделил `<h1> <p> <h2> <ol> <p> <ul> <p> <blockquote> <p> <img>` В `<footer>`  я ничего не отдалял т.к футер у нас один, и внутри него только один `<p>`.  Если я тебя правильно понял - подтверди что я молодец, если нет поясни чуть детаельней структуру разделения, а то если честно я тут уже сломал себе всю ГАЛАВУ пытаясь понять что нужно отделять а что не нужно)
P.S Сейчас обновлю код, смотри его если по моему описанию ничего не понятно)

**Comment by Demven** [comment]
Ты молодец!
Поправь три строчки где не нужна пустая строка.
Вообще, нет таких правил. Это я сам придумал, потому что удобнее читать верстку в таком формате. Плюс, помогает изолировать компоненты и визуально их выделять.

**Comment by Gr0mi4** [comment]
Принято, кажется я понял структуру, спасибо.
