### ISSUE TITLE
Page Scale (Масштаб)

### ISSUE THREAD

**Issue by Gr0mi4** [Gr0mi4/Hello-World#15]
Приветос! Слушай возник такой вопрос, в процессе выполнения нового задания я выяснил что новые страницы которые я создаю открываются не в том масштабе в котором я обычно работал со старой. Например: 
**Вот так я обычно вижу свою страницу на своем мониторе**
![image](https://user-images.githubusercontent.com/50546979/61692538-886a0700-ad36-11e9-811a-22c533e0576e.png)
**А вот так у меня загружаются новые страницы**
![image](https://user-images.githubusercontent.com/50546979/61692583-9e77c780-ad36-11e9-813b-6391102c6340.png)
Надеюсь ты понял что я имею ввиду. Мне приходится каждый раз подкручивать масштаб в ручную. Нагуглил что можно реализовать желательный масштаб через JS. Других способов нет?

**Comment by Demven** [comment]
Вань, что-то вообще не понял твою проблему: у меня все страницы выглядят одинаково. Не знаю что у тебя такое. Попробуй может другой браузер и сравни?

**Comment by Gr0mi4** [comment]
Они и у меня выглядят одинаково, но могу я задать масштаб в котором будет загружаться у людей страница? Например не 100% а 75%.... Правда я уже не уверен что стоит это делать, но все же)

**Comment by Demven** [comment]
Нет, не можешь, нафига это вообще нужно? Твой сайт должен адаптироваться сам под размер любого экрана. Мы это скоро начнем делать.
