### ISSUE TITLE
padding снизу

### ISSUE THREAD

**Issue by Gr0mi4** [Gr0mi4/Hello-World#19]
Привет! У меня такой вопрос:  Мы с тобой в начале говорили о том что в идеале Паддинги и Марджины должны быть только сверху, и слева. Ты ещё мне видос записывал. Я решил сегодня слегка разделить статьи, что бы визуально было понятно где заканчивается одна статья и начинается другая. 
Смотри картинку 1.
**Картинка 1**
![image](https://user-images.githubusercontent.com/50546979/62459925-3a6aef80-b789-11e9-879b-2d746a75c139.png)
Но мне хочется добавить расстояния между концом статьи и бордером, а то они как-то налезают друг на друга. Границу я задал через 
`.article {
border-bottom
}`
Подумав я понял что могу задать не нижнюю границу, а верхнюю и сделать как то так: 
`.article:not(:first-child) { top-bottom: 2px solid #efefef; margin-top: 10px padding-top: 10px}`
Или могу добавить небольшой марджин снизу для каждой статьи. Как правильнее?

**Comment by Demven** [comment]
Да, в твоем случае лучше указать границу сверху для последующих статей, все правильно. ЧТо касается отступа, то его можно задать через margin-top для последующей статьи, либо как padding-bottom для каждой статьи. Этот вариант наверное даже лучше, потому что этот отступ скорее является необходимой частью каждой статьи и статья не должна внезапно обрываться как только заканчвается текст, должен быть внизу паддинг.

**Comment by Gr0mi4** [comment]
Окей, тогда добавляю паддинг вниз
