### ISSUE TITLE
em и %

### ISSUE THREAD

**Issue by Gr0mi4** [Gr0mi4/Hello-World#24]
Привет! Мне нужно что бы ты мне объяснил в чем проблема в задании различных параметров с помощью процентов и ем? В курсе Юдасити совместном с гуглом который я смотрел по адаптивной верстке, говорили что проценты и емы ( а так же vh и vw)  на много более гибкие единицы, и больше подходят для адаптивной верстки, поэтому я их и пихал куда можно. Плюс например `left: 50%` или `border-radius: 50%` задают именно те размеры которые я хочу, и подбирать такие размеры через пиксели будет сложнее, и в зависимости от экрана положение будет меняться. Что делать в таких случаях?

**Comment by Demven** [comment]
С бордер-радиусом и left: 50% вопросов нет. Проценты сами по себе безумно важный и незаменимый инструмент. Но пихать его нужно только туда где это уместно.
Я наверное сделаю видео где с бумажкой и ручкой буду снова рисовать)

**Comment by Gr0mi4** [comment]
Окей, давай жду, потому что я не дорубаю где их можно использовать а где нет

**Comment by Gr0mi4** [comment]
Я понял суть по поводу ЕМов и процентов, но я с твоего позволения хочу оставить проценты в определении положения декоративных картинок в навигации (турбина и движок). Если проставить там пиксели то они остаются на одном месте, если проставлены проценты, то расстояние меняется вместе с изменением вьюпорта это удобно.

**Comment by Demven** [comment]
Да не вопрос
