### ISSUE TITLE
По поводу команд в консоли

### ISSUE THREAD

**Issue by Gr0mi4** [Gr0mi4/Hello-World#29]
Я пытался создать ещё одну команду в json файле, которая бы копировала файлы с картинками. 
Нашел вот такой вот модуль https://github.com/okunishinishi/node-filecopy, установил, но как он работает так и не понял. Если я правильно разобрался для копирования нужно задать переменную с именем файла или папки которые нужно скопировать. Как задать переменную в package.json я не знаю, то есть в каком месте какой синтаксис, и т.д. 
Поясни если не сложно, а вообще я хотел бы максимально детально разобраться с работой с npm и package.json что там можно писать куда и как, как пишутся скрипты и подобное. Если есть какая-то инфа было бы круто её почитать

**Comment by Demven** [comment]
Попробуй этот модуль https://www.npmjs.com/package/copyfiles
Хорошая документация, только написано что чтобы работало на винде нужно пути к файлам/папкам заключать в двойные кавычки ""
