### ISSUE TITLE
About Menuitem Tag

### ISSUE THREAD

**Issue by Gr0mi4** [Gr0mi4/Hello-World#3]
Warning: Currently the <menuitem> tag is not supported by the most of the web browsers like Chrome, IE, Safari, etc. Better you should avoid using this tag.
Found this on HTML5 web page, it seems ancient, (and working only in FireFox if i understand everything correct) does enybody use it now? What for? Should i?
And i don't shure about differences between menu and nav, they actually do same things, doesn't they? I've added menu to my web page, but still...

**Comment by Demven** [comment]
Right... My bad.
`<menu>` works only for context menus. Use the <ul> element instead.
https://www.w3docs.com/learn-html/html-menu-tag.html

**Comment by Demven** [comment]
It's should be smth like this:

```
<nav  class="navigation">
  <ul class="menu">
     <li class="menu-item">MAIN</li>
     <li class="menu-item">POSTS</li>
     ....
  </ul>
</nav>
```

**Comment by Demven** [comment]
@Gr0mi4 Did I answer your question? If so – close this issue :)
