### ISSUE TITLE
По поводу классов

### ISSUE THREAD

**Issue by Gr0mi4** [Gr0mi4/Hello-World#6]
Вопрос следующий: При написании кода, допустим я пишу отрезок текста, который я не хочу не как дополнительно форматировать. Например я пишу новую статью, или какую-то цитату. Меня устраивает то форматирование которое есть по умолчанию, нужно ли в таком случае определять класс для этой части текста? С одной стороны это даст мне возможность что-то поменять если я вдруг передумаю на счёт форматирования, с другой забивает классы которые я не использую. Как правильно?

**Comment by Demven** [comment]
Но очень понял вопрос, то в случае если у тебя есть статья с кучей параграфов и ты хочешь чтобы у всех было одно и то же форматирование, можешь сделать так:

```
<article class="blog-post">
  <p>Some text....</p>
  <p>Another text....</p>
  <p>And some text again....</p>

  <blockquote class="quote">
    <p>Text inside of a quote</p>
  </blockquote>
</article>
```

styles:

```
// стили для артикла (самого контейнера с текстовыми элементами)
.blog-post {
  padding: 24px;
}

// стили для параграфов, непосредственно в статье
// селектор ">" применяет стили непосредственно к первому уровню "детей" родительского элемента (если параграф будет внутри цитаты, например, то эти стили к нему не применятся)
.blog-post > p {
  font-family: Georgia;
  font-size: 16px;
  line-height: 19px;
}

.blog-post > ul {
  // стили для списков внутри статьи
}
```

**Comment by Demven** [comment]
Делать так вполне допустимо, при условии что твои стили не будут влиять на другие элементы, на которые тебе не нужно влиять (пример - параграф внутри цитаты).

Однако, опять-таки, использовать теги в качестве селектора не лучший вариант, гораздо лучше будет добавить класс на параграфы и сделать вот так:

**Comment by Gr0mi4** [comment]
Нет, ты немного не понял о чем я, а теперь я не уверен что полностью понимаю о чем ты)) Давай сначала - вот я пишу код:
<p class="text"> Бла бла бла </p> 
Я присвоил этому тексту класс text. Но в CSS файле, я этот класс использовать не буду, мне это тупо не надо, устраивает меня его форматирование сейчас. Оно определятся там чем угодно но не этим классом. Я просто создал этот класс для отдельного элемента на случай если вдруг захочу поменять КОНКРЕТНО ЭТОТ ВОТ элемент текста. Потом. То есть решил я например потом - ага, хочу выделить его красным шрифтом, а у меня уже он забит как класс мне даже не нужно лезть в HTML файл,  просто доабавить строку в CSS. Вопрос - это опытными прогерами (тобой) расценивается как ошибка (мол в жопу лишние классы), или всем пофигу делай как тебе удобнее? Я имею ввиду может куча не используемых классов загружают систему, или ещё чего? Опять таки в свете той статьи которые ты мне давал читать, весь файл потом пересылается на сервак а лишние классы = линий вес, так?  
З.Ы. Прости, я чем дальше пишу тем больше понимаю тупость вопроса, но мне нужно понять где пол а где потолок и чем хороший код отличается от плохого))) так что первое время мне нужно позадавать тупые вопросы) Сори)

**Comment by Demven** [comment]
Понимаешь ли, класс определяет сущность. Скажем вот есть кнопка:

```
<button class="submit-button">Submit</button>
```

Здесь "submit-button" описывает сущность и не важно заданы ли стили для нее или нет.  Когда ты откроешь инспектор кода, то ты увидишь "submit-button" и сразу  станет понятно что это ит для чего. Потом ты захочешь найти в своем приложении среди тысячи файлов  где у тебя эта кнопка и ты сделаешь поиск по всем файлам "submit-button" и найдешь нужный файл и нужное место.

Затем, допустим, когда кнопка нажали и, пока данные грузятся, ты хочешь показать это сделав кнопку неактивной чтобы ее не нажали еще раз, ты можешь добавить ей состояние "disabled":

```
.submit-button {
  background:  black;
  cursor: pointer;
}

.submit-button.disabled{
  background:  gray;
  cursor: not-allowed;
}
```
