### ISSUE TITLE
!DOCTYPE html

### ISSUE THREAD

**Issue by Gr0mi4** [Gr0mi4/Hello-World#7]
Хотел уточнить по поводу этого тега. В книге читал что мол это правило хорошего тона, сразу объявлять все ниже идущее хтмл документом такой надписью <!DOCTYPE html>, но когда я попробовал её добавить к своей странице, у меня перестали работать некоторые мои настройки по стилю, и я снёс эту надпись, т.к он все только усложняла) Расскажи что она вообще делает (потому что в книге вроде говорилось что она ничего не делает) и нужно ли её на самом деле вставлять в документ?

**Comment by Demven** [comment]
https://www.tutorialrepublic.com/html-tutorial/html-doctypes.php

Эта инструкция браузеру чтобы он понимал какую версию HTML ты используешь. Для HTML 5 она выглядит очень просто: `<!DOCTYPE html>` и это обязательно должна быть первая строчка в html файле.

Если ты не указываешь doctype  - браузер автоматически применяет HTML 5.
Ни за что не поверю что у тебя что-то сломалось после того как ты добавил доктайп. Скорее всего ты его как-то криво добавил и твой HTML стал невалидным. Добавь доктайп и покажи мне что у тебя сломалось.

Кстати, у тебя в файле один закрывающий тег неправильный: 

<img width="483" alt="image" src="https://user-images.githubusercontent.com/4939520/59113269-b6c08e00-8912-11e9-84b4-c298de795dd3.png">

**Comment by Gr0mi4** [comment]
Окей, сделаю скрины

**Comment by Gr0mi4** [comment]
Не сделаю скрины, ничего не изменилось)) Ты прав. Короче <DOCTYPE html> пишем всегда, думаю суть понятна. Ещё в книге говорилось про кодировку, но я уже сам понял что её НУЖНО писать когда открывал свой сайт на IE. Помню ещё про то что можно задавать язык lang=ru что то в этом роде. Есть ещё какие-то обязательные так называемые теги такого рода, которые я не знаю?

**Comment by Demven** [comment]
Да, lang задавать очень правильно. Потом очень важно прописывать метатеги. Но мы до этого еще дойдем.

**Comment by Gr0mi4** [comment]
Ок
