### ISSUE TITLE
Про display: inline-block против display: table-cell

### ISSUE THREAD

**Issue by Gr0mi4** [Gr0mi4/Hello-World#8]
По поводу того что ты написал в телеге. Я немного потупил, но разобрался как сделать такой же эффект какого я добился с помощью `display: table-cell`. НО! По умолчанию любой блочный элемент занимает всю доступную ширину. Для того что бы я мог поместить два элемента в строку мне необходимо задать ширину блоков `.aside` и `.article`, и если c картинкой данный момент не имеет значения, вот текст остается такой же ширины, как я задал, и не меняется если например я уменьшаю окно. Другими словами - окно становится меньше размера текста и не читается, а текст не подстраивается, хотя в случае `table-cell` все отражалось правильно. То есть я думаю для экранов разного размера, это ни есть гуд. Есть какое-то свойство или способ сделать так как нужно используя inline-block?

**Comment by Gr0mi4** [comment]
Помучился ещё немного. Ширину рекламы можно и не задавать, но без задания ширины блока `.article` - никак.

**Comment by Demven** [comment]
Помести артикл и рекламу  в один контейнер с  фиксированной шириной (например 1024px), и отцентрируй  его по центру экрана (`margin: 0 auto`).

```
<div class="content">
  <article ...
  
  <aside ...
<div>
```

**Comment by Gr0mi4** [comment]
А это не плохо, с точки зрения семантики? Мы же говорили о том что мы постоянно должны использовать специальные теги для каждого отдельного элемента?

**Comment by Gr0mi4** [comment]
У Меня `.article` и `.aside` лежат в разделе `<main>` с классом соответственно `.main.` Я могу задать ширину всего `.main` - это не правильно?

**Comment by Gr0mi4** [comment]
Крутая штука у меня все получилось. НО! Тут нужны разъяснения, а именно - как ты когда пишешь сайты и не можешь подстроиться под размеры мониторов всех пользователей, поступаешь с шириной?

**Comment by Demven** [comment]
> А это не плохо, с точки зрения семантики? Мы же говорили о том что мы постоянно должны использовать специальные теги для каждого отдельного элемента?

Ну правильно – для артикла – есть `article`, для "стороннего" контента – `aside` и тд. А все остальное – это просто вспомогательные элементы `div`.

**Comment by Demven** [comment]
> Крутая штука у меня все получилось. НО! Тут нужны разъяснения, а именно - как ты когда пишешь сайты и не можешь подстроиться под размеры мониторов всех пользователей, поступаешь с шириной?

Это называется адаптивная верстка. Мы до этого скоро дойдем)
