### ISSUE TITLE
А еще у тебя навигация поломана. Тебе нужно сделать их 'display:  inline-block' и задать им правильный margin. Типа такого:

### ISSUE THREAD

**Issue by Gr0mi4** [Gr0mi4/Hello-World#9]
А еще у тебя навигация поломана. Тебе нужно сделать их 'display:  inline-block' и задать им правильный margin. Типа такого:
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/4939520/59208511-351d6a00-8b77-11e9-959e-d3adb4964d07.png">

_Originally posted by @Demven in https://github.com/Gr0mi4/Hello-World/pull/4#issuecomment-500472659_

Я поменял, но не понял что изменилось, почему тебе не нравился мой паддинг, и вообще почему поломана?

**Comment by Demven** [comment]
Я же тебе скриншот показывал. Скорее всего у тебя экран больше моего и на моем оно не влазит и ломается.

**Comment by Demven** [comment]
Попробуй окно браузера уменьшить

**Comment by Gr0mi4** [comment]
![image](https://user-images.githubusercontent.com/50546979/59331761-6162f300-8cfd-11e9-942b-bd4630751a8a.png)
Вот что у меня получается после изменений уже. Я немного не о том спрашивал. Что ты имеешь под поломана?)) Я же не знаю как она должна себя вести, объясни на всякий как должна себя вести, и как вела себя у меня, на будущее что бы я понимал

**Comment by Demven** [comment]
Ну ты уже прямо до размеров мобильника уменьшил. В Пределах 1024px - считай что это десктоп и на десктопе навигация должна быть в одну строку и все должно быть аккуратно как по дизайну.
Адаптация под мобильники и планшеты будем делать позже отдельно. Пока должно работать на десктопе любых размеров.
